site_name: Catalyst Build System Documentation
theme:
  name: material
  logo: assets/logo.svg

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Installation: installation.md
  - Concepts:
    - Overview: concepts/index.md
    - Catalystignore: concepts/catalystignore.md
    - Configuration: concepts/configuration.md
    - Dependencies: concepts/dependencies.md
    - Environment Variables: concepts/environment-variables.md
    - Hooks: concepts/hooks.md
    - Log: concepts/log.md
    - Preprocessor: concepts/preprocessor.md
    - Profiles: concepts/profiles.md
    - Toolchains: concepts/toolchains.md
    - Workspaces: concepts/workspaces.md
  - CLI Reference:
    - Overview: cli/index.md
    - add: cli/add.md
    - bench: cli/bench.md
    - build: cli/build.md
    - clean: cli/clean.md
    - doc: cli/doc.md
    - download: cli/download.md
    - feature_ls: cli/feature_ls.md
    - fetch: cli/fetch.md
    - fmt: cli/fmt.md
    - generate: cli/generate.md
    - ide-sync: cli/ide-sync.md
    - init: cli/init.md
    - install: cli/install.md
    - lock: cli/lock.md
    - pack: cli/pack.md
    - profile_ls: cli/profile_ls.md
    - run: cli/run.md
    - test: cli/test.md
    - tidy: cli/tidy.md
  - Contributing: CONTRIBUTING.md
  - License: LICENSE.md
