#!/usr/bin/env python3
import argparse
import sys
from typing import List, Optional

class Subcommand:
    def __init__(
        self,
        name: str,
        ns: str,
        header: Optional[str] = None,
        app_member: Optional[str] = None,
        res_member: Optional[str] = None,
        brief: Optional[str] = None,
    ):
        self.name = name
        self.ns = ns
        self.header = header
        self.app_member = app_member or f"{name}_subc"
        self.res_member = res_member or f"{name}_res"
        self.brief = brief

# List of primary subcommands in their declaration order in dispatch.hpp
subcommands: List[Subcommand] = [
    Subcommand("add", "add", "add.hpp", brief="add"),
    Subcommand("build", "build", "build.hpp", brief="build"),
    Subcommand("clean", "clean", "clean.hpp", brief="clean"),
    Subcommand("download", "download", "download.hpp", brief="download"),
    Subcommand("fetch", "fetch", "fetch.hpp", brief="fetch"),
    Subcommand("fmt", "fmt", "fmt.hpp", brief="fmt"),
    Subcommand("generate", "generate", "generate.hpp", brief="generate"),
    Subcommand("ide_sync", "ide_sync", "ide_sync.hpp", brief="ide-sync"),
    Subcommand("init", "init", "init.hpp", brief="init"),
    Subcommand("install", "install", "install.hpp", brief="install"),
    Subcommand("introspect", "introspect", "introspect.hpp", brief="introspect"),
    Subcommand("lock", "lock", "lock.hpp", brief="lock"),
    Subcommand("run", "run", "run.hpp", brief="run"),
    Subcommand("test", "test", "test.hpp", brief="test"),
    Subcommand("bench", "bench", "bench.hpp", brief="bench"),
    Subcommand("tidy", "tidy", "tidy.hpp", brief="tidy"),
    Subcommand("pack", "pack", "pack.hpp", brief="pack"),
    Subcommand("doc", "doc", "doc.hpp", brief="doc"),
    Subcommand("profile_ls", "profile_ls", "profile_ls.hpp", app_member="profiles_ls_subc", brief="profile-ls"),
    Subcommand("feature_ls", "feature_ls", "feature_ls.hpp", brief="feature-ls"),
    Subcommand("completion", "completion", "completion.hpp", brief="completion"),
]

# List of nested/sub-subcommands in their declaration order in dispatch.hpp
nested_subcommands: List[Subcommand] = [
    Subcommand("git", "add::git", app_member="add_git_subc", res_member="add_git_res", brief="add git"),
    Subcommand("system", "add::system", app_member="add_system_subc", res_member="add_system_res", brief="add system"),
    Subcommand("local", "add::local", app_member="add_local_subc", res_member="add_local_res", brief="add local"),
    Subcommand("vcpkg", "add::vcpkg", app_member="add_vcpkg_subc", res_member="add_vcpkg_res", brief="add vcpkg"),
    Subcommand("conan", "add::conan", app_member="add_conan_subc", res_member="add_conan_res", brief="add conan"),
]

def generate_content() -> str:
    # Gather all headers from primary subcommands and sort them alphabetically
    headers = sorted([sub.header for sub in subcommands if sub.header])
    includes_str = "\n".join(f'#include "catalyst/subcommands/{h}"' for h in headers)

    # Generate member declarations
    all_subs = subcommands + nested_subcommands
    members_list = []
    for sub in all_subs:
        if sub.brief:
            member_decl = (
                f"    /// @brief CLI11 App for the {sub.brief} subcommand.\n"
                f"    CLI::App *{sub.app_member}{{nullptr}};\n"
                f"    /// @brief Parse result for the {sub.brief} subcommand.\n"
                f"    std::unique_ptr<catalyst::{sub.ns}::Parse> {sub.res_member}{{nullptr}};"
            )
        else:
            member_decl = (
                f"    CLI::App *{sub.app_member}{{nullptr}};\n"
                f"    std::unique_ptr<catalyst::{sub.ns}::Parse> {sub.res_member}{{nullptr}};"
            )
        members_list.append(member_decl)

    members_str = "\n\n".join(members_list)

    # Full template
    template = f"""#pragma once
// Automatically generated by scripts/generate_dispatch.py. Do not edit manually.

#include <memory>
#include <span>
#include <string_view>

#include <CLI11.hpp>

#include "catalyst/globals.hpp"
{includes_str}
#include "catalyst/utils/result.hpp"
#include "catalyst/workspace.hpp"

namespace catalyst {{
struct CliContext {{
    CLI::App app{{"Catalyst " + CATALYST_VERSION + " is a Modern Declarative C++ Build System."}};
    std::optional<Workspace> workspace;
    bool show_version{{false}};
    bool helped{{false}};

{members_str}
}};

std::pair<int, bool> parseCli(int argc, char **argv, catalyst::CliContext &ctx);
std::pair<int, bool> parseCli(std::string_view args, catalyst::CliContext &ctx);
std::pair<int, bool> parseCli(std::span<const std::string> args, catalyst::CliContext &ctx);
int dispatch(const catalyst::CliContext &ctx);
Result<void> dispatchHook(std::string_view args);
Result<void> dispatchHook(std::span<const std::string> args);
}} // namespace catalyst
"""
    return template

def main():
    parser = argparse.ArgumentParser(description="Generate include/catalyst/dispatch.hpp")
    parser.add_argument(
        "-o", "--output",
        help="Output file path. If not specified, output is written to stdout."
    )
    args = parser.parse_args()

    content = generate_content()

    if args.output:
        try:
            with open(args.output, "w", encoding="utf-8") as f:
                f.write(content)
            print(f"Successfully generated dispatch header at: {args.output}")
        except Exception as e:
            print(f"Error writing to file {args.output}: {e}", file=sys.stderr)
            sys.exit(1)
    else:
        sys.stdout.write(content)

if __name__ == "__main__":
    main()
